# Generated by Django 3.0.8 on 2020-07-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='job_image/'),
            preserve_default=False,
        ),
    ]
