# Generated by Django 3.0.8 on 2020-07-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='JobApply',
        ),
    ]
