# Generated by Django 3.0.8 on 2020-07-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20200722_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobapply', to='job.Job'),
            preserve_default=False,
        ),
    ]
